### PR TITLE
Merge Configable NeatFeatures & Outrons

### LINKED ISSUE #931: "outrons" not rendered with neat features
For features that start and/or end with introns (apparently called "outrons" sometimes), NeatCanvasFeatures doesn't render them at all, though JBrowse is aware that there is more to the feature, since it draws the strand arrows in the right place (which is visually confusing, since the strand arrow is sitting out there in nowheresville).  This may also be an issue with NeatHTMLFeatures but I haven't tested it.  Example screenshots are below.

"regular" features"
regular features

Neat features:
neatfeatures

### PR DESCRIPTION
**Pull request by enuggetry**
Fix #988 Configurable Neat Features
Fix #931 Render Outrons

### CODE REVIEW

**Comment by rbuels** [comment]
@enuggetry is this ready to test and review?

**Comment by nathandunn** [comment]
I just went through and my only comment is that the default for NeatHTMLFeatures is off and the default for NeatCanvasFeatures is on.    

You probably want both off or both on as the default.    

However, the configuration and backing text both look great. 💯

**Comment by rbuels** [comment]
When testing this, I'm getting a bunch of errors in the console like this:

http://localhost:8080/?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A1..19524&tracks=DNA%2CCDS%2Cmalformed_alignments%2Cvolvox_vcf_test%2CEST%2CExampleFeatures%2CReadingFrame%2CClones%2CNameTest&highlight=

image

Could you have a look at that @enuggetry ?

**Comment by rbuels** [comment]
Is there any way we can disable the gradient by default for alignments tracks?  The mismatch markers clash terribly with the gradient:

image

**Comment by enuggetry** [comment]
Will work on it.
- [ ]  default NeatHTMLFeatures off??
- [ ]  type error appendChild
- [ ]  disable for alignments

**Comment by enuggetry** [comment]
Addressed in #1011

**Pull request closed without merging**
