### PR TITLE
JS ports of add-track-json.pl and remove-track.pl, with push notifications via Faye

### PR DESCRIPTION
**Pull request by ihh**
Since this includes our first dynamic server code, and therefore mildly consequential in its design (even though it's not that much actual code and still pretty much firewalled from everything else), I am posting it as a pull request to invite discussion.

This is a straightforward port of the Perl scripts add-track-json and remove-track, with options to send push notifications (via a minimal faye-based message server) to the client, which pretty much echoes the relevant messages straight to the internal event system.

I added a couple extra initialization milestones for the faye message server, and left most message channels unrestricted, so that plugins can hook into the message system and communicate easily between running JBrowse instances.

### CODE REVIEW

**Comment by ihh** [comment]
hmmm - the travis builds are failing due to my attempt at including a non-AMD file (the faye browser client) in an AMD 'define' statement (at the start of Browser.js)

it works on my setup - not sure why travis didn't get the memo

**Comment by cmdcolin** [comment]
Looks awesome. The travis builds are kind of picky. Probably, specifically, the build/minification step. I think that it is possible to fix it though, maybe by inserting the non-AMD dependency another way. Apollo does this by manually injecting the script tags https://github.com/GMOD/Apollo/blob/master/client/apollo/js/main.js#L81-L92. There are also "loader" plugins for dojo apparently that can help too

**Comment by cmdcolin** [comment]
I added the branch https://github.com/GMOD/jbrowse/tree/faye-mod which fixes the build https://travis-ci.org/GMOD/jbrowse/builds/113932360

It just includes faye in index.html and also updates git submodules

Converted tabs to spaces as well

**Comment by ihh** [comment]
Thanks @cmdcolin 

I actually prefer the Apollo way of doing it, i.e. manually injecting script tags into the document head, so I added this to faye-mod.

Unfortunately in doing so I seem to have reverted the git submodules and it's complaining when i try to update them. This is a case of git confusing the hell out of me; I can't seem to figure out how to update the dijit submodule, it's complaining of dozens of file conflicts and I don't want to force it when I don't understand it. Any ideas?

I haven't yet tried the Travis build on faye-mod so I don't know if Travis will complain but I think there's a fair chance it will work.

At least I have fixed my emacs javascript mode so it will no longer do tabs :)

**Comment by ihh** [comment]
In the process of f**king around, I also seem (somehow) to have committed your faye-mod edits (where the script tag is in index.html) over to the faye branch, and left my edits (where the script tag is inserted by Browser.js) on the faye-mod branch. I have no idea how this happened. THANKS OBAMA

**Comment by ihh** [comment]
tumblr_n5vv4cbr8y1tojh0do1_250

**Comment by cmdcolin** [comment]
Lol!

>This is a case of git confusing the hell out of me; I can't seem to figure out how to update the dijit submodule, it's complaining of dozens of file conflicts and I don't want to force it when I don't understand it. Any ideas?

I think that I don't have a good answer for that except a fresh clone can help. Might look into a better command for it I mentioned that on #666  having same issue with updating the submodule, and reverting to just a new git clone --recursive.

Might be possible to go into the "src/dojo" "src/dijit" "src/dojox" "src/util" and manually "git fetch && git checkout 1.8.10", but not sure

I think can go ahead and push that script change from faye-mod back to this branch faye for the fix (with the submodules up to date)

**Comment by cmdcolin** [comment]
baaef72 includes the change you made

Also, given the pain of the git submodules (which are basically like git clones inside of a git clone, pretty awkward) we might consider managing dependencies with something like bower too. I think dojo and friends are fine with bower, and faye might be able to be managed that way too.

#333 demonstrates that

**Comment by harshuopi** [comment]
What would be the differences between the branches `faye` and `faye-mode`?

**Comment by harshuopi** [comment]
What would be the differences between the branches `faye` and `faye-mod`?

**Comment by ihh** [comment]
@harshuopi None, I think we can delete faye-mod now, right @cmdcolin ?

**Comment by cmdcolin** [comment]
@ihh yep. everything from that branch merged onto faye now

**Comment by childers** [comment]
I'm glad that you guys worked it out!

https://xkcd.com/1597/

**Comment by harshuopi** [comment]
I wanted to know where do you want to take this PR forward?

**Comment by harshuopi** [comment]
I made a little feature in which you can share the link to all the instances of jbrowse connected to faye server. Clicking on the link will automatically push the url. And it will get logged in the console (for now) of all the jbrowse instances.

screenshot from 2016-03-10 14-14-13

Do you think it will be a step forward?

**Comment by rbuels** [comment]
What's the status of this? Is this still a thing or can we close it?

**Comment by enuggetry** [comment]
I'd like to suggest we refactor this to use socket.io, given it is part of the sails framework that is used by JBServer.   And, the event handling can be applied in a plugin, like the JBClient plugin portion of JBserver.
JBserver can add/update/delete tracks through web service, with broadcast.  perhaps the cli can be rolled into JBServer.  Just a thought.

**Comment by ihh** [comment]
It really should be possible to do this in JBrowse Connect — this Faye demo was, after all, the prototype that came before Connect. I’m wary of adding new features to a project so over budget although, as noted, they aren’t really “new”. And it seems like Connect is already capable of doing this.

Rolling the cli into Connect - you mean the add-track scripts? We don’t want Connect to be required for normal operation of jbrowse, so that’s a non-starter unless I’m missing something.

So yes I’d go along with exposing this capability in Connect (assuming it is in fact basically already there) and closing this issue.

**Comment by ihh** [comment]
*closing this PR (sorry am on my GitHub app on my phone - easy to get mixed up)

**Pull request closed without merging**
