### PR TITLE
Fix usage of TS vs ts

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a special case handling to fix the bug in #1484 but it is slightly awkward, not sure if there is a better way to do this.

### CODE REVIEW

**Comment by rbuels** [comment]
Oh man. Yeah I guess that's about as good as can be gotten.

Attributes are case-sensitive in JB2, so we should be OK there I hope.

**Comment by cmdcolin** [comment]
Yep. It might be that bam-js should adopt a similar thing to cram-js records with the tags() method, but it would no longer become a lazy feature if it does that (there might be some middleground though, not sure)

**Comment by cmdcolin** [comment]
The contents of this PR were changed so that now it doesn't use case sensititve, it just uses the "useXS" and applies to TS tag while the user interface clarifies that useTS applies to the lower case `ts` tag from minimap

Screenshot from 2020-05-11 14-31-02

**Comment by cmdcolin** [comment]
Fix on dev

**Pull request merged**
