### PR TITLE
Handled a case that str is not a string

### PR DESCRIPTION
**Pull request by hkmoon**
Added toString() because we faced an issue where str is not a string and replace() cannot be called while testing intermine integration

If you think this place is not a good place to put toString(), feel free to change it.

### CODE REVIEW

**Comment by rbuels** [comment]
Looks good, thanks!

**Comment by cmdcolin** [comment]
Note that this PR was merged onto master instead of dev

**Comment by cmdcolin** [comment]
I say that because probably good to keep in mind that our PR workflow should merge onto dev :)

**Comment by rbuels** [comment]
Argh didn’t notice that it was going to master. I’ll back it out. I wonder
if that was a side effect of changing the default branch

**Comment by cmdcolin** [comment]
Ya PR will by default be sent to master, it is kind of annoying

**Pull request merged**
