### PR TITLE
Moving labels canvasfeatures

### PR DESCRIPTION
**Pull request by cmdcolin**
This PR adds support for moving the canvasfeatures labels while scrolling, referencing issue #390

One caveat is that there is a small moment where the "renderLabel" rendering and the "updateStaticElements" from this PR are both visible at the same time. Not sure if there is a good fix (maybe clearRect over region?)

Screenshot
screenshot-localhost-2018-02-01-23-39-52-502

### CODE REVIEW

**Comment by rbuels** [comment]
a.) could you add a release-notes blurb about this?

b.) aren't the strand arrows just drawn as updatable static elements?  probably the labels should be the same, don't you think?  can we just disable the renderLabel rendering of the labels?

**Comment by cmdcolin** [comment]
I added a small change to help move towards option making it only an updateStaticFeatures thing. It works ok with single box features but with gene glyph the "bounds" of the fRect aren't expanded so the text overlaps feature on initial render (and, as noted above, the transcript labels overlap the transcripts during scrolling also, some question of whether this is desirable)

Screenshot, you can see that even when the label is not being "kept visible" the transcript labels overlap the feature. Normally the transcript labels are moved to the left of the feature.
screenshot-localhost-2018 02 27-21-10-08

**Comment by rbuels** [comment]
does the gene glyph need to be fixed to make that work then?

**Comment by cmdcolin** [comment]
this is a little weird but it seems like maybe a little tinier clearrect boundary might help, otherwise surrounding feature labels seem to get clipped




```
diff --git a/src/JBrowse/View/FeatureGlyph/Box.js b/src/JBrowse/View/FeatureGlyph/Box.js
index 3c1682e..4ca2021 100644
--- a/src/JBrowse/View/FeatureGlyph/Box.js
+++ b/src/JBrowse/View/FeatureGlyph/Box.js
@@ -313,7 +313,7 @@ return declare([ FeatureGlyph, FeatureLabelMixin], {
                 context.font = fLabelRecord.font
                 context.fillStyle = fLabelRecord.fill
                 context.textBaseline = fLabelRecord.baseline
-                context.clearRect(labelLeft,labelTop,fLabelRecord.w,fLabelRecord.h)
+                context.clearRect(labelLeft,labelTop,fLabelRecord.w,fLabelRecord.h*0.7)
                 context.fillText(
                     fLabelRecord.text,
                     labelLeft,

```

**Comment by cmdcolin** [comment]
also the feature labels kind of go a little crazy when you click zoom out

**Comment by rbuels** [comment]
@cmdcolin thanks for pointing those out, I fixed those two issues in dev

**Comment by cmdcolin** [comment]
Awesome:))!

**Pull request merged**
