### PR TITLE
Refactor Neat features as track types

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a reworking of NeatHTMLFeatures and NeatCanvasFeatures into track types

This could be considered a non-starter though because it creates the NeatHTMLFeatures and NeatCanvasFeatures as track types, but that could make integration with apollo difficult since apollo derives from HTMLFeatures, not NeatHTMLFeatures. Not sure if there is an easy workaround for that

This also has the side effect of fixing #651

### CODE REVIEW

**Comment by enuggetry** [comment]
Thanks. 
I guess it's not as seamless, due the need for trackType in the track config.
I was hopeful it would solve #890, but guess it's not related.  In fact, with this, bug #890 is also exhibited in NeatHTMLFeatures.

**Comment by cmdcolin** [comment]
Both NeatCanvasFeatures and NeatHTMLFeatures with this PR have a "gradient" boolean config that can be enabled

**Comment by enuggetry** [comment]
Oh, it's default off.  I see.

**Comment by nathandunn** [comment]
So, I think this is fine, in principle (making them first-class track types), though the existing implementations have a few bugs, which is why they are not not the default for Apollo:

https://github.com/GMOD/APOLLO/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20neatfeatures%20

I think we need to retain the plugin, though, as I don't think we are going to implement the track types in Apollo with those bugs.   I run a lot of my sites with HTMLNeatFeatures on, and it looks cool, but it is hardly robust enough for production without some fixing.

**Comment by cmdcolin** [comment]
I think this is probably going to go into 1.15.0! It does require the track type is explicitly declared to be NeatCanvasFeatures but I think there are a lot of wins with this route. I know there are some prominent neat features users so if anyone has feedback I'd be interested in knowing. @jogoodma

**Comment by nathandunn** [comment]
I agree.  This is the right way to go on this and it will make maintenance of it easier.

**Comment by cmdcolin** [comment]
There are two caveats to this PR which is that 

- gradients dont work on NeatHTMLFeatures, presumably due to trying to grab the style of the element before it is rendered to the dom
- unannotated utr/outron not rendered in this code (canvas features has inferUTRs basically for this)

I imagine there can be a workaround to those issues but if those aren't roadblockers maybe this can still move forward

**Pull request merged**
