### PR TITLE
upgrade google analytics to analytics.js and add optional parameter to record pageviews for one or more non-JBrowse Analytics users

### PR DESCRIPTION
**Pull request by rdhayes**
Switched to analytics.js syntax and added new jbrowse.conf selfGoogleUsageAccount parameter (single value or comma-separated list of additional Google Analytics accounts to report page views)

This test URL is reporting correctly to our Phytozome Google Analytics:
https://phytozome.jgi.doe.gov/analyticsPatch/index.html?data=genomes%2FGmax

To complete this, I need the following from someone with access to the JBrowse Google Analytics:
1) Verify that you see page views for /analyticsPatch/ directories after viewing the above URL.
2) Set up "Custom dimensions" or "custom metrics" for the JBrowse account to accept the values provides for 'tracks-count', 'refseqs-count', 'refSeqs-avgLen', 'jbrowse-version', and 'loadTime', as now configured in lines 1706-1710. These are the old ga.js "custom variables", but the analytics.js API changed.

### CODE REVIEW

**Comment by rdhayes** [comment]
I was being too fancy and splitting a multi-line string on '\', but that's fixed. I think that means we're just waiting on analytics reporting confirmation and custom dimension setup and verification. As for the latter, the Chrome Google Analytics plugin does report:
    Set called on unknown field: "tracks-count".
etc. for each of the current jbrowseTracker.set ga directives and makes a good test for dimension/metric support.

**Comment by enuggetry** [comment]
Nice!  I'll come back around to you on this.

**Comment by rdhayes** [comment]
Hi,

This patch is live on Phytozome, and you should hopefully see jbrowse.org traffic for the https://phytozome.jgi.doe.gov domain. I don't believe the ga.js CustomVar replacements will show up without some config changes on your end, e.g. like this example conversion to analytics.js "custom dimensions":

analyticsScript += "ga('jbrowseTracker.set', 'tracks-count', "+stats['tracks-count']+");";

**Comment by nathandunn** [comment]
I think that @enuggetry  or @rbuels  may be able to verify that, but I don't know how they would identify you individually.    Maybe shoot an email to them off-line to make sure.   The changes looked good.

**Comment by rdhayes** [comment]
I recall an email thread from September 2017 where Eric verified receiving phytozome.jgi.doe.gov page views.

**Pull request merged**
