### PR TITLE
Electron app

### PR DESCRIPTION
**Pull request by cmdcolin**
Basic ideas:

- Uses the current codebase without much modification
- Has a Makefile build step for packaging with the minimized codebase (which produces exe's for win,osx,linux)
- Adds an "Open data directory" menu option to the electron app
- Ability to open indexed FASTA (and retains un-indexed FASTA mode, but alerts if over 100MB)

Updated 12/01

### CODE REVIEW

**Comment by enuggetry** [comment]
Very nice addition to jbrowse!  Ready to fly, out of the box.

**Comment by cmdcolin** [comment]
Added some updates

(a) Opening a data directory works now. Also, instead of using the browser teardown code, it simply refreshes the page with ?data=<that data folder>
(b) Opening an indexed fasta file works too. It creates a new trackList.json in the same folder as that indexed fasta, and then, similarly, refreshes the page with ?data=<the folder of the fasta file> (since writing the trackList.json there essentially initializes the data directory)


Put together, I think these two features makes the electron app quite usable.
Here's a new folder with links https://drive.google.com/folderview?id=0BxkRH5zBEJ33cFlsRlUtNXBTUHM&usp=sharing

**Comment by cmdcolin** [comment]
Updated the downloads with a small fix. Currently expects tracks.conf file to exist :)

**Comment by cmdcolin** [comment]
Reuploaded again https://drive.google.com/folderview?id=0BxkRH5zBEJ33cFlsRlUtNXBTUHM&usp=sharing

**Comment by cmdcolin** [comment]
Pushed a new fix for opening local files/paths on Windows https://drive.google.com/folderview?id=0BxkRH5zBEJ33cFlsRlUtNXBTUHM&usp=sharing

**Comment by cmdcolin** [comment]
Updated downloads

This works for opening an indexed FASTA file in both the webapp and electron-app

https://drive.google.com/folderview?id=0BxkRH5zBEJ33dDRHWWd0eFBkQkU&usp=sharing

**Comment by cmdcolin** [comment]
Alrighty I restored the ability to load the unindexed FASTA files now

It gives an "Are you sure" if it's over 100MB, and recommends using the FAI file :)

**Comment by enuggetry** [comment]
Nice.  Thanks.

**Comment by cmdcolin** [comment]
I was gonna go ahead and merge this! Lemme know if any objections

**Comment by enuggetry** [comment]
If you feel good about it, pls do.

**Comment by cmdcolin** [comment]
Alright!

**Pull request merged**
