### PR TITLE
Fix perl 5.18+ by adding sorting to hash keys where necessary

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a fix for #470

It addresses hash order randomization issues by just adding sorting to keys when they are evaluated. 

This fully improves the excessive running time and huge disk space issues encountered on perl 5.18+

This also tests for travis-ci to 5.16 and 5.18 (default for travis is to test 5.14). We could add more perl versions if there is interest but testing 5.16 and 5.18 gives us the "before & after hash order randomization test suite".

### CODE REVIEW

**Comment by rbuels** [comment]
Why does sorting hash keys fix this issue?  What has changed from earlier perl versions that is breaking things?

**Comment by keiranmraine** [comment]
We saw this in our tools too, it appears that perl 5.18+ actually enforces a more random response when sort is not specified (tends to be 2 states).  I think the idea being to highlight that although it has historically been stable on a platform/OS it isn't guaranteed between systems.

Also worth checking that there isn't any `keys $hashref` as that is now:

> Starting with Perl 5.14, an experimental feature allowed keys to take a scalar expression. This experiment has been deemed unsuccessful, and was removed as of Perl 5.24.

**Comment by cmdcolin** [comment]
Looks like this feature that landed in 5.18 http://www.perlmonks.org/?node_id=1005122

**Comment by cmdcolin** [comment]
Also as to why sorting fixes it, there are just certain tests that expect certain data to be in a certain order in the JSON or similar.

**Comment by enjoyyourcopepods** [comment]
I am wondering if the strange JSON files that were produced by the random hash ordering might cause problems with the way JBrowse displays annotations tracks.

**Comment by cmdcolin** [comment]
I don't believe this would have caused any problems with how tracks are displayed. It just caused many permutation of typed arrays to be created. You might open another issue if you have seen errors

**Pull request merged**
