### PR TITLE
Proposed fix for #596

### PR DESCRIPTION
**Pull request by sakshamsaxena**
PR is either way due for this little patch. Can discuss changes here itself, or go ahead with a merge maybe.

### CODE REVIEW

**Comment by cmdcolin** [comment]
This has the effect of making all dialog boxes (whether they are the "View details" popup or not) have this specific width so I think it might not be a good idea :). I think it's better to, as you said on the other issue, work with the fact that the dialog "autosizes" itself to the content. This goes the other way and forces all dialogs to be the specific width which changes all existing dialogs

Example: normally dialog not this wide but after this change it is made to be
default

**Comment by sakshamsaxena** [comment]
Ah I saw that one coming. Thanks for the heads up. I'm looking for another workaround meanwhile. Will push more commits to this PR soon.
________________________________

**Comment by sakshamsaxena** [comment]
Had to keep the window width constant, and the content width to auto so that the _content_ conforms to the window, as the other way round is actually already expected from the Dialog, but is clearly buggy.

**Comment by enuggetry** [comment]
I'll close this for now, until we find a better resolution.

**Pull request closed without merging**
