### PR TITLE
npm install jbrowse as a module

### PR DESCRIPTION
**Pull request by enuggetry**

### CODE REVIEW

**Comment by nathandunn** [comment]
Keep wondering if this could be used for plugins eventually, as well.

**Comment by enuggetry** [comment]
Yes, I had that in mind, too.

**Comment by nathandunn** [comment]
@enuggetry    I tried to install jbrowse for Apollo from within github by just issuing the command:

    npm install gmod/jbrowse#npm_install

It looks like there is a problem during the postinstall phase.   It seems like those should already be there.   Any ideas? 

```
npm install gmod/jbrowse#npm_install
-
> jbrowse@1.12.3 postinstall /home/ndunn/git/Apollo-staging/node_modules/jbrowse
> node utils/postinstall.js

>>> postinstall
appPath /home/ndunn/git/Apollo-staging modPath /home/ndunn/git/Apollo-staging/node_modules/jbrowse
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dojo']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dojo' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dojo']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dojo' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dijit']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dijit' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dojox']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dojox' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/jszlib']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/jszlib' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/json-schema']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/json-schema' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/lazyload']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/lazyload' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dgrid']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dgrid' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/jDataView']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/jDataView' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dojo-util']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dojo-util' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/filesaver.js']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/filesaver.js' }
error { [Error: ENOENT: no such file or directory, lstat '/home/ndunn/git/Apollo-staging/node_modules/dojo-dstore']
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ndunn/git/Apollo-staging/node_modules/dojo-dstore' }
jbrowse@1.12.3 node_modules/jbrowse
├── jDataView@1.1.0
├── electron-screenshot@1.0.5
├── filesaver.js@0.2.0
├── jszlib@0.0.1
├── node-getopt@0.2.3
├── app-root-path@2.0.1
├── json-schema@0.2.3
├── express@4.15.4 (setprototypeof@1.0.3, escape-html@1.0.3, array-flatten@1.1.1, cookie-signature@1.0.6, utils-merge@1.0.0, methods@1.1.2, content-type@1.0.2, merge-descriptors@1.0.1, encodeurl@1.0.1, cookie@0.3.1, content-disposition@0.5.2, fresh@0.5.0, parseurl@1.3.1, etag@1.8.0, path-to-regexp@0.1.7, range-parser@1.2.0, vary@1.1.1, serve-static@1.12.4, statuses@1.3.1, depd@1.1.1, qs@6.5.0, on-finished@2.3.0, finalhandler@1.0.4, proxy-addr@1.1.5, debug@2.6.8, send@0.15.4, type-is@1.6.15, accepts@1.3.3)
├── dojo-dstore@1.1.2
├── fs-extra@4.0.1 (universalify@0.1.1, jsonfile@3.0.1, graceful-fs@4.1.11)
├── lazyload@1.0.0
├── dgrid@1.2.1
├── shelljs@0.7.8 (interpret@1.0.3, glob@7.1.2, rechoir@0.6.2)
├── dojo-util@1.12.2
├── async@2.5.0 (lodash@4.17.4)
├── dojo@1.12.2
├── dijit@1.12.2
└── dojox@1.12.2
```

**Comment by nathandunn** [comment]
I *think* that it is still working when doing the install from Apollo (even with the post-install errors).    However, github is hanging for some reason.

**Comment by enuggetry** [comment]
@nathandunn you mention is happened without package.json in your app root.  But, I still couldn't reproduce it.  What platform are you using?

**Comment by nathandunn** [comment]
@enuggetry  It has something to do with the caching.  Let me mess with it a bit more.

**Pull request merged**
