### PR TITLE
Fix NeatCanvasFeatures - restore gradients

### PR DESCRIPTION
**Pull request by enuggetry**
Restores gradient features of NeatCanvasFeatures (issue #982)
Cleanup readme.md for both NeatHTMLFeatures and NeatCanvasFeatures

### CODE REVIEW

**Comment by cmdcolin** [comment]
It doesn't appear to me that gradient features are configurable at least from looking at code. Is the flag ignored?

**Comment by cmdcolin** [comment]
Also what was result of https://github.com/GMOD/jbrowse/pull/721 ? Why is this being changed back to gradient on by default?

**Comment by enuggetry** [comment]
I'll take a look later today and fix any that needs fixing.

**Comment by enuggetry** [comment]
by default the gradients should be on, as that's essentially what the plugin does.

**Pull request merged**
