### PR TITLE
Tabix bed

### PR DESCRIPTION
**Pull request by zhjilin**
BEDTabix
Got inspiration from @cmdcolin 's code. I cleaned my code for general purpose. Still I kept the function I used in case someone want to play around.
I ran a test on 1.11.6-dev with human data, it worked as shown in the attached screenshot (3 column bed, 6 column bed with show strand arrows and name spontaneously). It's appreciated if someone could run a final test to check the code, since I had several problems with setting up codes from github. 

screenshot-forbedtabix-pullreq

### CODE REVIEW

**Comment by enuggetry** [comment]
Nice job!  Thank you.

**Comment by keiranmraine** [comment]
Very happy to see this, shame it missed the release.

**Comment by vivekkrish** [comment]
:+1:

**Comment by cmdcolin** [comment]
As @zhjilin mentioned the branch was a little out of date so I brought it up-to-date here https://github.com/GMOD/jbrowse/tree/tabix_bed

Could close this PR and redo it with that branch

**Comment by keiranmraine** [comment]
Please can we get this merged into the next release 👍

**Comment by nathandunn** [comment]
Do you need it in mainline before the next release?

Nathan

**Comment by keiranmraine** [comment]
It would be very helpful if it could be, but I suspect #729 is more relevant, I spotted @cmdcolin had fixed it up after I commented (I've tested that version).

**Comment by nathandunn** [comment]
Sounds good.  Maybe I’ll let @cmdcolin and @eynuggetry look into it then. I’m sure it will be in the next release either way.

**Comment by cmdcolin** [comment]
Sure thing. Can forward to the other PR. This one can be closed as outdated

**Pull request closed without merging**
