### PR TITLE
Use Bower, instead of git submodules, for dependencies.

### PR DESCRIPTION
**Pull request by yeban**
yeban/afra builds on top of JB, which uses bower for dependency management. It's just easier for me to use bower all over instead of parts bower and parts 'git submodule'. And, it would become 10% easier for me to track upstream and report bugs / send PR. And that's the sole rationale for this PR.

"bower vs. git submodules" in general: with bower you can track both semantic versions and git branches (and arbitrary ref -- planned).

Testing:

    # assuming you have your test data/ dir in place

    $ python -m SimpleHTTPServer

    # visit localhost:8000 in browser, JB works

-- Priyam

---

Stick to the latest release of the dependencies that do semantic
versioning.

dojo         1.9.1
dojox        1.9.1
util         1.9.1
dijit        1.9.1
put-selector 0.3.4
dgrid        0.3.9
xstyle       0.2.0
json-schema  0.2.1

Except, lazyload.  The latest release of lazyload is 2.0.3, however, JB
uses an additional commit from Robert Buels which seems relevant.

dbind, jDataView, FileSaver.js and jszlib don't do semantic versioning.
So we stick to git 'master'.

jsdoc_toolkit-2.4.0, perl5, and wig2png are a part of source tree.
Nothing to bowerize there.

Signed-off-by: Anurag Priyam <anurag08priyam@gmail.com>

### CODE REVIEW

**Comment by cmdcolin** [comment]
Here's another project using bower to download dojo in a similar way to this pull request https://github.com/Esri/dojo-bootstrap-map-js

this is a good thing because it kind of confirms my suspicion;...bower is needed to get dojo instead of npm. i suspect the reason is that the npm dojo libs are minified and cant be used to produce further build packages

**Comment by nathandunn** [comment]
It would be good to think about this in terms of https://github.com/GMOD/Apollo/issues/194.  

That being said, I think that dojo is supported better by npm, but I am no expert:

http://stackoverflow.com/questions/22901693/bower-does-not-download-git-submodule-dojox-candidate-plugin

Of course, it am still bothered by the fact that they use git to distribute code.

**Comment by yeban** [comment]
Hey @cmdcolin. I have upped the version numbers of dojo universe dependencies since I created this PR. You may want to take a look - https://github.com/yeban/afra/blob/master/bower.json#L24.

**Comment by nathandunn** [comment]
@cmdcolin   I think that we'll want this (or something very close to it) for the Apollo 2 build.

**Comment by cmdcolin** [comment]
I think we can probably merge this and move towards the "npm/bower style". Besides, this is actually how they talk about using dojo on https://dojotoolkit.org/download/


Merging this commit should have no real side effects as far as jbrowse builds are concerned, but, notable, WebApollo workflows currently all use the "git clone --recursive" approach in the build process, so we might just want to merge this quickly before Apollo 2.0.0 is released?

**Comment by cmdcolin** [comment]
There's not a real urgency but I just thought i'd throw that out there.

**Comment by cmdcolin** [comment]
Probably need to update this to pass travis-ci with a bower install step. Otherwise yeban-bowerise branch seems ok.

**Comment by nathandunn** [comment]
:+1:

**Comment by cmdcolin** [comment]
The yeban-bowerise branch has travis-ci tests passing now  https://travis-ci.org/GMOD/jbrowse/builds/118352924


Can test with

    git clone --depth 1 --branch yeban-bowerise https://github.com/gmod/jbrowse.git
    bower install
    ./setup.sh

**Comment by enuggetry** [comment]
Not having too much luck with:

```
[eric@localhost jbrowse]$ bower install
bower install       jDataView#db0893d468
bower install       FileSaver#4f79d8e666
bower EACCES        EACCES, mkdir '/var/www/html/bower/jbrowse/src/json-schema'

Stack trace:
/usr/lib/node_modules/bower/lib/node_modules/fstream/lib/dir-writer.js:35:25
/usr/lib/node_modules/bower/lib/node_modules/mkdirp/index.js:46:53
Object.oncomplete (fs.js:108:15)

Console trace:
Error
    at StandardRenderer.error (/usr/lib/node_modules/bower/lib/renderers/StandardRenderer.js:83:37)
    at Logger.<anonymous> (/usr/lib/node_modules/bower/lib/bin/bower.js:110:26)
    at Logger.emit (events.js:95:17)
    at Logger.emit (/usr/lib/node_modules/bower/lib/node_modules/bower-logger/lib/Logger.js:29:39)
    at /usr/lib/node_modules/bower/lib/commands/index.js:48:20
    at _rejected (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:844:24)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:870:30
    at Promise.when (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:1122:31)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/bower/lib/node_modules/q/q.js:788:41)
    at /usr/lib/node_modules/bower/lib/node_modules/q/q.js:604:44
System info:
Bower version: 1.7.7
Node version: 0.10.36
OS: Linux 2.6.32-573.8.1.el6.x86_64 x64
[eric@localhost jbrowse]$ sudo mkdir '/var/www/html/bower/jbrowse/src/json-schema'
[eric@localhost jbrowse]$
```

logged in as root: 
```
[root@localhost jbrowse]# bower install
bower ESUDO         Cannot be run with sudo

Additional error details:
Since bower is a user command, there is no need to execute it with superuser permissions.
If you're having permission errors when using bower without sudo, please spend a few minutes learning more about how your system should work and make any necessary repairs.

http://www.joyent.com/blog/installing-node-and-npm
https://gist.github.com/isaacs/579814

You can however run a command with sudo using --allow-root option
[root@localhost jbrowse]#

```

**Comment by nathandunn** [comment]
Try the other pull request and let me know if you get the same result.  You'll have to delete the src directories for bower to use them.  

Nathan

**Comment by enuggetry** [comment]
Pretty much the same problem using #718

**Comment by nathandunn** [comment]
Hmm . . thanks I’ll take a look. 

Nathan

**Comment by nathandunn** [comment]
If you have existing src directories it won’t work, but otherwise it should.  

Maybe . . . the bower commands should all go in setup.sh?  In there I can detect if .git modules have been downloaded and delete appropriately? 

Nathan

This is my test (for #718):

$git clone https://github.com/GMOD/jbrowse/
$cd jbrowse
$git checkout yeban-bowerise
$bower install 


bower not-cached    git://github.com/rbuels/jDataView.git#*
bower resolve       git://github.com/rbuels/jDataView.git#*
bower not-cached    git://github.com/rbuels/jszlib.git#*
bower resolve       git://github.com/rbuels/jszlib.git#*
bower not-cached    git://github.com/dkasenberg/FileSaver.js.git#*
bower resolve       git://github.com/dkasenberg/FileSaver.js.git#*
bower not-cached    git://github.com/rbuels/lazyload.git#amd
bower resolve       git://github.com/rbuels/lazyload.git#amd
bower not-cached    git://github.com/rbuels/dbind.git#*
bower resolve       git://github.com/rbuels/dbind.git#*
bower cached        git://github.com/kriszyp/json-schema.git#0.2.1
bower validate      0.2.1 against git://github.com/kriszyp/json-schema.git#0.2.1
bower cached        git://github.com/dojo/util.git#1.9.2
bower validate      1.9.2 against git://github.com/dojo/util.git#1.9.2
bower cached        git://github.com/kriszyp/put-selector.git#0.3.6
bower validate      0.3.6 against git://github.com/kriszyp/put-selector.git#0.3.6
bower cached        git://github.com/dojo/dojox.git#1.9.2
bower validate      1.9.2 against git://github.com/dojo/dojox.git#1.9.2
bower cached        git://github.com/SitePen/dgrid.git#0.3.17
bower validate      0.3.17 against git://github.com/SitePen/dgrid.git#0.3.17
bower cached        git://github.com/dojo/dojo.git#1.9.2
bower validate      1.9.2 against git://github.com/dojo/dojo.git#1.9.2
bower cached        git://github.com/dojo/dijit.git#1.9.2
bower validate      1.9.2 against git://github.com/dojo/dijit.git#1.9.2
bower cached        git://github.com/kriszyp/xstyle.git#0.3.1
bower validate      0.3.1 against git://github.com/kriszyp/xstyle.git#0.3.1
bower checkout      dbind#master
bower checkout      jszlib#master
bower checkout      jDataView#master
bower checkout      FileSaver#master
bower checkout      lazyload#amd
bower invalid-meta  dbind is missing "main" entry in bower.json
bower invalid-meta  dbind is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/dbind.git#2b70834f3b
bower invalid-meta  jszlib is missing "main" entry in bower.json
bower invalid-meta  jszlib is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/jszlib.git#18cd14e592
bower invalid-meta  FileSaver is missing "ignore" entry in bower.json
bower resolved      git://github.com/dkasenberg/FileSaver.js.git#4f79d8e666
bower invalid-meta  jDataView is missing "main" entry in bower.json
bower invalid-meta  jDataView is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/jDataView.git#db0893d468
bower invalid-meta  lazyload is missing "main" entry in bower.json
bower invalid-meta  lazyload is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/lazyload.git#d428749c54
bower install       put-selector#0.3.6
bower install       json-schema#0.2.1
bower install       util#1.9.2
bower install       dgrid#0.3.17
bower install       dojox#1.9.2
bower install       dijit#1.9.2
bower install       xstyle#0.3.1
bower install       dojo#1.9.2
bower install       dbind#2b70834f3b
bower install       jszlib#18cd14e592
bower install       FileSaver#4f79d8e666
bower install       jDataView#db0893d468
bower install       lazyload#d428749c54

put-selector#0.3.6 src/put-selector

json-schema#0.2.1 src/json-schema

util#1.9.2 src/util

dgrid#0.3.17 src/dgrid

dojox#1.9.2 src/dojox

dijit#1.9.2 src/dijit

xstyle#0.3.1 src/xstyle

dojo#1.9.2 src/dojo

dbind#2b70834f3b src/dbind

jszlib#18cd14e592 src/jszlib

FileSaver#4f79d8e666 src/FileSaver

jDataView#db0893d468 src/jDataView

lazyload#d428749c54 src/lazyload

 
$./setup.sh 

Installing Perl prerequisites ... done.

Formatting Volvox example data ... done.
To see the volvox example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/volvox.

Formatting Yeast example data ... done.
To see the yeast example data, browse to http://your.jbrowse.root/index.html?data=sample_data/json/yeast.

Building and installing legacy wiggle format support (superseded by BigWig tracks) ... failed.  See setup.log file for error messages. If you really need wig-to-json.pl (most users don't), make sure libpng development libraries and header files are installed and try running setup.sh again.

Building and installing legacy bam-to-json.pl support (superseded by direct BAM tracks) ... done.

$python -m SimpleHTTPServer

Going to URL:

http://localhost:8000/index.html?data=sample_data%2Fjson%2Fvolvox&loc=ctgA%3A20001..30001&tracks=DNA&highlight= <http://localhost:8000/index.html?data=sample_data/json/volvox&loc=ctgA:20001..30001&tracks=DNA&highlight=>

works. 

Nathan

**Comment by cmdcolin** [comment]
I think the issues that @enuggetry mentions are permissions related (bower EACCES        EACCES, error indicates that)

I would take ownership of the files in the folder (i.e. similar to the chown command here http://jbrowse.org/code/JBrowse-1.12.1/docs/tutorial/, or maybe chown -R)

Also, in general, SimpleHTTPServer doesn't support byte range requests for BAM files, etc. so it is better to just test on a normal server

**Comment by nathandunn** [comment]
It has similar problems if any existing git submodule is already there, as well.  I'm going to close this in favor of #718 in order to push further changes.

**Comment by cmdcolin** [comment]
Sounds right, the yeban-bowerise branch is the one up to date now :)

**Comment by enuggetry** [comment]
As root, this works, adding the **--allow-root** option.


```
[root@localhost jbrowse]# bower install -f --allow-root
bower resolve       git://github.com/dojo/util.git#1.9.2
bower resolve       git://github.com/rbuels/jDataView.git#*
bower resolve       git://github.com/rbuels/jszlib.git#*
bower resolve       git://github.com/dkasenberg/FileSaver.js.git#*
bower resolve       git://github.com/kriszyp/json-schema.git#0.2.1
bower resolve       git://github.com/rbuels/lazyload.git#amd
bower resolve       git://github.com/rbuels/dbind.git#*
bower checkout      jszlib#master
bower checkout      jDataView#master
bower checkout      FileSaver#master
bower download      https://github.com/kriszyp/json-schema/archive/v0.2.1.tar.gz
bower download      https://github.com/dojo/util/archive/1.9.2.tar.gz
bower resolve       git://github.com/dojo/dijit.git#1.9.2
bower resolve       git://github.com/dojo/dojox.git#1.9.2
bower resolve       git://github.com/kriszyp/put-selector.git#0.3.6
bower resolve       git://github.com/SitePen/dgrid.git#0.3.17
bower resolve       git://github.com/dojo/dojo.git#1.9.2
bower checkout      dbind#master
bower checkout      lazyload#amd
bower resolve       git://github.com/kriszyp/xstyle.git#0.3.1
bower download      https://github.com/dojo/dijit/archive/1.9.2.tar.gz
bower invalid-meta  jszlib is missing "main" entry in bower.json
bower invalid-meta  jszlib is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/jszlib.git#18cd14e592
bower invalid-meta  FileSaver is missing "ignore" entry in bower.json
bower resolved      git://github.com/dkasenberg/FileSaver.js.git#4f79d8e666
bower download      https://github.com/dojo/dojox/archive/1.9.2.tar.gz
bower download      https://github.com/kriszyp/put-selector/archive/v0.3.6.tar.gz
bower invalid-meta  jDataView is missing "main" entry in bower.json
bower invalid-meta  jDataView is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/jDataView.git#db0893d468
bower download      https://github.com/SitePen/dgrid/archive/v0.3.17.tar.gz
bower extract       json-schema#0.2.1 archive.tar.gz
bower download      https://github.com/dojo/dojo/archive/1.9.2.tar.gz
bower invalid-meta  json-schema is missing "main" entry in bower.json
bower invalid-meta  json-schema is missing "ignore" entry in bower.json
bower download      https://github.com/kriszyp/xstyle/archive/v0.3.1.tar.gz
bower resolved      git://github.com/kriszyp/json-schema.git#0.2.1
bower invalid-meta  dbind is missing "main" entry in bower.json
bower invalid-meta  dbind is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/dbind.git#2b70834f3b
bower invalid-meta  lazyload is missing "main" entry in bower.json
bower invalid-meta  lazyload is missing "ignore" entry in bower.json
bower resolved      git://github.com/rbuels/lazyload.git#d428749c54
bower extract       put-selector#0.3.6 archive.tar.gz
bower retry         Download of https://github.com/dojo/dojo/archive/1.9.2.tar.gz failed with ECONNRESET, retrying in 1.2s
bower invalid-meta  put-selector is missing "main" entry in bower.json
bower invalid-meta  put-selector is missing "ignore" entry in bower.json
bower resolved      git://github.com/kriszyp/put-selector.git#0.3.6
bower extract       dijit#1.9.2 archive.tar.gz
bower extract       xstyle#0.3.1 archive.tar.gz
bower extract       dgrid#0.3.17 archive.tar.gz
bower invalid-meta  xstyle is missing "main" entry in bower.json
bower invalid-meta  xstyle is missing "ignore" entry in bower.json
bower resolved      git://github.com/kriszyp/xstyle.git#0.3.1
bower extract       util#1.9.2 archive.tar.gz
bower invalid-meta  dgrid is missing "main" entry in bower.json
bower invalid-meta  dgrid is missing "ignore" entry in bower.json
bower resolved      git://github.com/SitePen/dgrid.git#0.3.17
bower extract       dojo#1.9.2 archive.tar.gz
bower invalid-meta  util is missing "main" entry in bower.json
bower invalid-meta  util is missing "ignore" entry in bower.json
bower resolved      git://github.com/dojo/util.git#1.9.2
bower invalid-meta  dijit is missing "main" entry in bower.json
bower invalid-meta  dijit is missing "ignore" entry in bower.json
bower resolved      git://github.com/dojo/dijit.git#1.9.2
bower extract       dojox#1.9.2 archive.tar.gz
bower invalid-meta  dojo is missing "main" entry in bower.json
bower invalid-meta  dojo is missing "ignore" entry in bower.json
bower resolved      git://github.com/dojo/dojo.git#1.9.2
bower invalid-meta  dojox is missing "main" entry in bower.json
bower invalid-meta  dojox is missing "ignore" entry in bower.json
bower resolved      git://github.com/dojo/dojox.git#1.9.2
bower install       jszlib#18cd14e592
bower install       FileSaver#4f79d8e666
bower install       jDataView#db0893d468
bower install       json-schema#0.2.1
bower install       dbind#2b70834f3b
bower install       lazyload#d428749c54
bower install       put-selector#0.3.6
bower install       xstyle#0.3.1
bower install       dgrid#0.3.17
bower install       util#1.9.2
bower install       dijit#1.9.2
bower install       dojo#1.9.2
bower install       dojox#1.9.2

jszlib#18cd14e592 src/jszlib

FileSaver#4f79d8e666 src/FileSaver

jDataView#db0893d468 src/jDataView

json-schema#0.2.1 src/json-schema

dbind#2b70834f3b src/dbind

lazyload#d428749c54 src/lazyload

put-selector#0.3.6 src/put-selector

xstyle#0.3.1 src/xstyle

dgrid#0.3.17 src/dgrid

util#1.9.2 src/util

dijit#1.9.2 src/dijit

dojo#1.9.2 src/dojo

dojox#1.9.2 src/dojox

```

**Comment by nathandunn** [comment]
Hmm . . . so maybe have something like this?  Not sure how the rest of the script works.


BOWER_OPTION=“"
if [[ $EUID -eq 0 ]]; then
   BOWER_OPTION=“ —allow-root “
fi

bower install -f $BOWER_OPTION

**Comment by enuggetry** [comment]
As user, this is what worked for me:
sudo bower install -f --allow-root
sudo ./setup.sh

I also had to setup in /etc/sudoers, the NOPASSWD option for my users.

**Comment by nathandunn** [comment]
I think that makes sense, especially if you’re installing directly as root into apache. 

Nathan

**Pull request closed without merging**
