### PR TITLE
Add support to index names for gff tabix (#780)

### PR DESCRIPTION
**Pull request by billzt**
Modified according to the functions of vcf names indexing. Aim to fix the fourth bug in #780

### CODE REVIEW

**Comment by cmdcolin** [comment]
this is great! does this only index the ID of the features? it could be useful to index other fields, possibly at the user's command

**Comment by billzt** [comment]
Yeah, this would be a little more complicated than vcf. Perhaps adding a novel parameter to `generate-names.pl` is more robust. However I'm not sure whether it is acceptable.

**Comment by cmdcolin** [comment]
at least one thing that is sort of interesting is that with normal flatfile-to-json.pl on a gff file, you use the --nameAttributes parameter of flatfile-to-json.pl to determine what parameters of the gff you want to have indexed by generate-names.pl


so, potentially if the gff3tabix was incorporated into flatfile-to-json.pl then it might hook into that parameter

**Comment by nathanhaigh** [comment]
Would this work for GFF3 files on remote storage? e.g. the `baseUrl` is an http address.

**Comment by rbuels** [comment]
@billzt sorry about the delay here.  Would you be willing to add a test case for this to the automated tests in `tests/perl_tests/generate-names.pl.t?

**Pull request merged**
