### PR TITLE
Makes legacy software install an optional extra

### PR DESCRIPTION
**Pull request by keiranmraine**
As requested, @nathandunn

### CODE REVIEW

**Comment by nathandunn** [comment]
@keiranmraine   I think you need to update the .travis.yml as follows:

```
git diff
diff --git a/.travis.yml b/.travis.yml
index 189124c..7bdcbd6 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -15,7 +15,7 @@ before_install:
   - npm install -g jshint bower
 install:
   - bower install
-  - bash setup.sh
+  - bash setup.sh legacy
 before_script:
   - cat tests/travis.conf | envsubst > tests/travis-envsubst.conf
   - nginx -c `pwd`/tests/travis-envsubst.conf
```

Also, when I run the script (with a prior install) it hangs after I run setup.sh (with or without the legacy option) with the follwogin message:

```
%./setup.sh
Bower dependencies already installed.  Type '/usr/local/bin/bower install -f --allow-root' to force reinstallation of dependencies.
```

**Comment by cmdcolin** [comment]
Looks like it doesn't actually do anything with the LEGACY_INSTALL flag, so this has a no-op effect

**Comment by nathandunn** [comment]
Closing in favor of #827.

**Comment by keiranmraine** [comment]
@cmdcolin it exited before the perl install if `$LEGACY_INSTALL -eq 0`:

https://github.com/keiranmraine/jbrowse/blob/d71c0e0108c9c0b92ccd78add18ed584e338e5be/setup.sh#L164-L167

**Comment by cmdcolin** [comment]
yep missed that. I was expecting an if statement around the other things but early exit works. looks good!

**Comment by cmdcolin** [comment]
merged in #827

**Comment by nathandunn** [comment]
Oh, I'd fixed that in #871 by removing the exit from the legacy message that was called initially.

**Comment by cmdcolin** [comment]
It might be nice if the echo -n is added back.

Previously it would just say

Installing perl prerequisites...

And then a few seconds later one the same line add "done"

**Comment by nathandunn** [comment]
Yeah, that's fine so long as they all do the:

Doing xyz .... done

Nathan

**Pull request closed without merging**
