### PR TITLE
Fixed VCF with/without dummy tests

### PR DESCRIPTION
**Pull request by garrettjstevens**
Hi @rbuels, hopefully this doesn't mess you up, but I fixed these two tests while working with VCF stuff, so I figured I'd try saving you some work by adding them to your branch, too.

### CODE REVIEW

**Comment by cmdcolin** [comment]
I just pushed this straight onto dev :) changed the floating point toEqual to toBeCloseTo also

**Comment by cmdcolin** [comment]
Feel free to reopen if the specific changes are more relevant to this branch e.g. the removal of the index load manually

**Comment by garrettjstevens** [comment]
Hey @cmdcolin, thanks for the toBeCloseTo fix, I'm still getting used to how JavaScript handles numbers. I'm going to go ahead and re-open this PR, though, since `store.indexedData.index.load()` doesn't work on this branch because of the new Tabix interface. That was the main reason I did this change, the added `expect` was just something extra I threw in.

**Comment by cmdcolin** [comment]
You can generally run a command "yarn patch" to bump the version (or yarn minor or yarn major) these are in the package.json

**Comment by garrettjstevens** [comment]
@cmdcolin, my `yarn` doesn't seem to recognize `patch` as a command? I used `yarn version --patch` in the tabix-js repo to update that package. I just didn't know if there was a better way to update tabix-js as a dependency in jbrowse besides just updating it in the `package.json` and re-running `yarn`.

Also, now that this branch is passing tests I'm going to check the performance on #1195 and see if it's any different.

**Comment by cmdcolin** [comment]
Oh nevermind tabix and jbrowse don't have that in their package.json :) carry on!

**Comment by garrettjstevens** [comment]
@rbuels I pulled in the latest changes to this branch to get rid of the merge conflicts.

**Pull request merged**
