### PR TITLE
[WIP/RFC] Interactive Tours

### PR DESCRIPTION
**Pull request by erasche**
Please do not merge, this is work-in-progress, and I just wanted to open the PR early to solicit feedback.

jbrowse-tut

Features:
- [ ] UI
  - [x] Nice popups which generally float where you want them to and help highlight interesting elements
  - [x] next/back buttons & progress indicators. 
  - [x] HTML available in tutorial message.
  - [x] Real interactivity (i.e. make users click on things/interact with JBrowse to move to the next item.)
  - [ ] Shadowbox/overlay to de-emphasize the rest of the UI
- [ ] Tours
  - [x] easy to write tours in yaml format (because newlines are no fun in json/javascript) which are converted to JSON
  - [x] Basic genome movement
  - [ ] Tracks
  - [ ] Advanced tutorial?
- [x] Implementation Details
  - [x] change .json load path to a relative one.

### CODE REVIEW

**Comment by erasche** [comment]
Open questions:

- Can I trigger zooming on specific regions from an API? (I.e. where do I look for this in the codebase)
- Features you (devs + community) would like to see? 
- Things that everyone feels should be covered by a tutorial

**Comment by enuggetry** [comment]
That's pretty nice!

You can generally navigate to anywhere with
browser.navigateTo(searchString), where the searchString is basically
anything you can access from the search field.  i.e. searchString = "
ctgA:7408..30008";

For zooming with animation:
browser.view.zoomIn()
browser.view.zoomOut()

Vertical position:
browser.view.setPosition({x:0,y:50})  // keep x=0

**Comment by erasche** [comment]
@enuggetry oh excellent, thanks!

**Comment by erasche** [comment]
@enuggetry suggested listening to track turned on events emitted, in order to show track specific tutorials.

**Comment by cmdcolin** [comment]
Just wanted to add a +1 to this in some fashion. Lots of "hidden features" and a little tour like this would be great to get people accustomed...

**Comment by erasche** [comment]
Closing this in lieu of a completely separate plugin since it's nice enough to just add HTTP urls to JBrowse.conf that it isn't necessary to have it in core.

**Pull request closed without merging**
