### PR TITLE
In setup.sh, add check to suppress running biodb-to-json.pl if system is on MacOS High Sierra

### PR DESCRIPTION
**Pull request by deepakunni3**
This PR is to address the issue observed in https://github.com/GMOD/Apollo/issues/1820

While running `setup.sh`, the `biodb-to-json.pl` step keeps running indefinitely while it generates large temp files to the point of filling all available disk space.

The behavior is observed only on **MacOS High Sierra**. 

This PR modifies `setup.sh` to check if the system is on MacOS High Sierra and skip running `biodb-to-json.pl` if it is.

@nathandunn @enuggetry

### CODE REVIEW

**Comment by nathandunn** [comment]
I'll test through this shortly.   In the interim, could you raise / find an issue here and add that as well to the echoed comments.   You can copy me on so that it subscribes me automatically.

https://github.com/bioperl/bioperl-live/issues

**Comment by nathandunn** [comment]
That is almost instant.  Wow.  Yes, good to go once we have a reference for the bioperl issue.    The reason for this is for someone to say "hey, its fixed now".   I can create it instead if you prefer.

**Comment by deepakunni3** [comment]
Did not create an issue on the BioPerl issues page because this issue might be occurring within Perl scripts packaged with JBrowse, one of which is `biodb-to-json.pl`.
If we find that its upstream to JBrowse then we can create an issue and reference it here.

**Comment by rbuels** [comment]
@deepakunni3 could you add a line about this in the release-notes.txt?

**Comment by rbuels** [comment]
Just update this pull request with the release-notes addition and I'll merge it

**Comment by nathandunn** [comment]
Actually @rbuels , the "Gathering System Information" takes forever. I think its just the system_profiler call.  Is it necessary for the non-legacy build?

**Comment by deepakunni3** [comment]
@nathandunn Its not "Gathering System Information". 

I do agree that the sytem_profiler call does take its time on MacOS, but its not the main cause of this issue.

I debugged through the entire `setup.sh` script to pin point the exact place where it was getting stuck. And that is at running `biodb-to-json.pl` step. If I comment that out for Volvox and Yeast, everything works fine.

**Comment by nathandunn** [comment]
That’s right.  It’s all coming back to me.  Ignore my previous statement. 

Nathan

**Comment by rbuels** [comment]
@deepakunni3 could you add a line about this in the release-notes.txt and update this branch with it? Or just add it to master and mention "#945" in the commit message so that it's linked here?

**Comment by rbuels** [comment]
[It's all coming back to me too](https://www.youtube.com/watch?v=pDxoj-tDDIU&t=5m14s)

**Comment by nathandunn** [comment]
Those are some fond memories

Nathan

**Comment by cjfields** [comment]
@rbuels The issue is on systems with versions of berkeley-db compiled on older Mac OS X releases (along with any Perl libraries like DB_File compiled against it) which are upgraded to High Sierra (and APFS).  The issue in the Apple forum:

https://discussions.apple.com/thread/8125401

I have seen this with both the system perl and perlbrew installations; the only workarounds I found: 

1. Install a separate version of berkeley-db from brew or fink, then reinstall DB_File.  This seemed the fastest route; I'm not sure whether the system version is updated, but a clean version can be installed via fink or brew
2. Run a clean installation of perl with a recompiled version of berkeley-db.

**Pull request merged**
