### PR TITLE
fixes #743

### LINKED ISSUE #743: NeatHTMLFeatures fails to draw intron clearly when zoomed in
On zoom, we may need to redraw and add/or additional angle to the intron being drawn.

### LINKED ISSUE #755: NeatCanvasFeatures do not display UTR
screen shot 2016-06-02 at 3 22 20 pm

### PR DESCRIPTION
**Pull request by nathandunn**
@enuggetry  I think that this fixes #743.  

I think that somebody already fixed #755 as I can't seem to reproduce it and it was pretty easy to do before.

### CODE REVIEW

**Comment by nathandunn** [comment]
@enuggetry  I'm not sure if this is exactly the right solution.   It still get this error, though I think its an improvement. 

Here I'm off to the side (there should be an intron to the left).  Its the Honeybee Group11.4:27056..27220, Official Gene Set v3.2:

screen shot 2016-12-16 at 2 52 16 pm

Zoomed in I get this error (which I should have fixed), since I'm just drawing a straight line instead of a line that goes to the LHS of the exon at right:

screen shot 2016-12-16 at 2 54 15 pm

These *MAY* be due to the second feature in scope to the left, but I actually don't think so.  Just a guess.

**Comment by nathandunn** [comment]
From @enuggetry:

git diff -U0 -w --no-color | git apply --cached --ignore-whitespace --unidiff-zero -             
git diff --cached

```
 git diff --cached
diff --git a/src/JBrowse/View/Track/HTMLFeatures.js b/src/JBrowse/View/Track/HTMLFeatures.js
index a4f67a2..051962c 100644
--- a/src/JBrowse/View/Track/HTMLFeatures.js
+++ b/src/JBrowse/View/Track/HTMLFeatures.js
@@ -1323,7 +1323,12 @@ var HTMLFeatures = declare( [ BlockBased, YScaleMixin, ExportMixin, FeatureDetai
 
         // if the feature has been truncated to where it doesn't cover
         // this subfeature anymore, just skip this subfeature
-        if ( subEnd <= displayStart || subStart >= displayEnd )
+
+                var truncate = false;
+                if (typeof this.config.truncateFeatures !== 'undefined' && this.config.truncateFeatures===true )
+                    truncate = true;
+
+                if ( truncate && (subEnd <= displayStart || subStart >= displayEnd) )
             return null;
 
         if (Util.is_ie6) subDiv.appendChild(document.createComment());
```

**Comment by nathandunn** [comment]
@enuggetry  This works beautifully for me.

**Comment by nathandunn** [comment]
thanks

**Comment by mpoelchau** [comment]
@nathandunn - is this fixed in Apollo2.0.6-SNAPSHOT? We noticed the same problem. Currently using: 

Version: 2.0.6-SNAPSHOT
Grails version: 2.5.5
Groovy version: 2.4.4
JVM version: 1.8.0_112

**Comment by nathandunn** [comment]
@mpoelchau  This should be fixed now (well as of 20 days ago).   What are you currently seeing on your master build?  

Also, did you and @childers install with a clean-all in order to get the correct version of JBrowse.   Most likely you did.

**Comment by childers** [comment]
@nathandunn I generally use clean-all, but to be safe I ran clean-all, rebuilt and deployed. I'll clear my browser caches and check it out once the deployment finishes.

**Comment by nathandunn** [comment]
@childers   I thought you probably did.  What are you and @mpoelchau  seeing (screenshot if you have one).

**Comment by childers** [comment]
I still see the double intron. The image below was taken in private mode, and testing it on a naive browser (Opera) showed the same thing. Do you see this on HTML features? Also, do you still see the disappearing introns at some zooms in your builds?

apollo206-post-rebuild

**Comment by nathandunn** [comment]
@childers  These are two separate issues.  This is issue https://github.com/GMOD/Apollo/issues/1415 . .. not sure if its an Apollo or a JBrowse issue.

**Comment by childers** [comment]
Oh, to make matters more confusing, I enabled one of the other htmlDragableFeature tracks, and it only has one intron line.  At certain zoom levels it disappeared, but I could not replicate the behavior.

apollo-new-look2

**Comment by mpoelchau** [comment]
The clean-all and rebuild got rid of the missing intron problem. Thanks!

**Comment by nathandunn** [comment]
@mpoelchau  is this the problem in https://github.com/GMOD/Apollo/issues/1415?  

Either way, glad it is working ;)

**Comment by mpoelchau** [comment]
The problem referenced earlier in this issue - missing introns when zoomed in - is fixed.

The problem @childers mentioned earlier in this thread - which is actually https://github.com/GMOD/Apollo/issues/1415 - isn't.

**Pull request merged**
