### PR TITLE
Add removeCollapsedClick and removeCollapsedMouseover options

### PR DESCRIPTION
**Pull request by cmdcolin**
This is a PR to address https://github.com/GMOD/jbrowse/issues/544

This PR adds two config options

`removeCollapsedClick` - is false by default, but can be made true to address @rdhayes concern
`removeCollapsedMouseover` - remains true by default, but it can be made false to allow mouseovers to where the collapsed features are non-overlapping

Therefore track behavior is by default the same as previous jbrowse versions, but with these added config enhancements.

This also adds a sample demo track to volvox data with "segmentation" data

### CODE REVIEW

**Comment by rdhayes** [comment]
Hi, I'll test this out this week, but that should clean up collapsed display in my view. To go one step further, I'd like to add a new track-level mouseover when in "collapsed" state that triggers a switch to "normal" display. Do you have any advice on which dojo Milestone to track in this case?

"/jbrowse/v1/c/tracks/show" or "/jbrowse/v1/n/tracks/redraw"? or perhaps both? 

Thanks!

**Comment by cmdcolin** [comment]
>>I'd like to add a new track-level mouseover when in "collapsed" state that triggers a switch to "normal" display

That is kind of a weird use case but could grant it. I guess I'd probably not want to switch between "collapsed and normal" really suddenly but it could work
In any case the jbrowse events don't really track mouseovers if that's what you are asking, you can use the jbrowse events to dynamically edit the config in-place by using something like browser.publish('/jbrowse/v1/v/tracks/replace', [newconfig]);

**Comment by rbuels** [comment]
@cmdcolin What do you think about renaming these to `disabledCollapsed*` instead `removeCollapsed*`.  A new user would think that "remove" would imply that you remove features when you collapse them or something.

I like that there is more test data now, that's a good addition.

I brought this branch up to date with the latest master, so that it gets the selenium tests running in travis.
@cmdcolin @rdhayes Would one of you be willing to add a selenium test for this?

**Comment by cmdcolin** [comment]
Sounds good to me. I renamed them enableCollapsedMouseover and disableCollapsedClick to make it easier (e.g. if you want either of these settings, you set them to true, rather than wrapping around a double negative of setting disableCollapsedMouseover to false)

If I can get selenium running locally I can look into adding a test for it

**Comment by rbuels** [comment]
```
pip install nose selenium
./jb_run.js -p 8080 &
SELENIUM_BROWSER=firefox JBROWSE_URL='http://localhost:8080/index.html' nosetests
SELENIUM_BROWSER=chrome JBROWSE_URL='http://localhost:8080/index.html' nosetests
```

**Comment by cmdcolin** [comment]
I added a small selenium test that ensures that I get a mouseover when the track is collapsed based on the volvox sample data now :)

**Comment by rbuels** [comment]
could you add a release-notes blurb about this?

**Comment by cmdcolin** [comment]
Added the blurb :)

**Pull request merged**
