### PR TITLE
Updated twobitsupport

### PR DESCRIPTION
**Pull request by cmdcolin**
This is an updated PR from #309 to allow 2bit files to be loaded 

This adds support to load it via the web browser or in the electron app.

This makes it quite easy to load common genomes and doesn't require an extra FASTA index, since 2bit is already indexed.

### CODE REVIEW

**Comment by cmdcolin** [comment]
Would propose merging too! Fairly modular data loader :)

**Comment by cmdcolin** [comment]
The error with the sequences is fixed now. It was due to requesting negative coordinates at the start of the chromosome, which was similarly an issue when we did the fasta code and easily fixed by sitting it to 0 if it's negative.

Should be ready now

**Comment by keiranmraine** [comment]
@cmdcolin , are there any docs for how to configure for 2bit, I can't see an modifications to `prepare-refseqs.pl` indicating how to configure it.  Also do you know if this would be going into the next release?

**Comment by cmdcolin** [comment]
Actually that's a good point. I pushed some changes to allow using --twobit with prepare-refseqs.pl

**Comment by bslaff** [comment]
Will the --twobit option for prepare-refseqs.pl be added to the master branch?

**Comment by cmdcolin** [comment]
I can get this merged and a couple of other ones that were discussed if there's interest

**Comment by nathandunn** [comment]
Yes, I think that is the plan.  Thanks.

**Comment by cmdcolin** [comment]
Alright, just gonna press the big green button here!

**Pull request merged**
