### PR TITLE
Replace bower with npm

### PR DESCRIPTION
**Pull request by cmdcolin**
Repost of #886 

Fixes issues with bigwig/vcf that were noted at the end of that thread. Reason was due to some weird issues after upgrading jdataview library noted here https://github.com/jDataView/jDataView/issues/83

So this version sticks with same jdataview library on master branch

### CODE REVIEW

**Comment by nathandunn** [comment]
@cmdcolin  Is this ready for review / testing (I'm assuming you removed the in progress label because of that)?   If so, I'll take a look.    Excited to get that in there.

**Comment by cmdcolin** [comment]
Sure, welcome to try

**Comment by nathandunn** [comment]
@cmdcolin    This looks good.  I tested it with both Apollo and straight JBrowse.    @enuggetry said he would take a gander as well.  

Thanks for doing this.

**Comment by enuggetry** [comment]
Thanks a bunch.
The git clone path looks good.
However, I ran into problems trying to install as npm package.  (this doesn't have to be a merge holdup, though).
```
$ npm install GMOD/jbrowse#replace_bower_with_npm

> jbrowse@ postinstall /var/www/html/3jbserver/node_modules/jbrowse
> bash postinstall.sh

cp: cannot stat ‘node_modules/dojo’: No such file or directory
cp: cannot stat ‘node_modules/dijit’: No such file or directory
cp: cannot stat ‘node_modules/dojox’: No such file or directory
cp: cannot stat ‘node_modules/jszlib’: No such file or directory
cp: cannot stat ‘node_modules/lazyload’: No such file or directory
cp: cannot stat ‘node_modules/dgrid’: No such file or directory
cp: cannot stat ‘node_modules/jDataView’: No such file or directory
cp: cannot stat ‘node_modules/dojo-util’: No such file or directory
cp: cannot stat ‘node_modules/filesaver.js’: No such file or directory
cp: cannot stat ‘node_modules/dojo-dstore’: No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! jbrowse@ postinstall: `bash postinstall.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the jbrowse@ postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ericiam/.npm/_logs/2017-07-13T21_05_06_366Z-debug.log
```

**Comment by cmdcolin** [comment]
I didn't necessarily expect installing as a package in that way to work, even though that would be cool. You'd probably have to hack the postinstall script even more to just put directories in the right location.

**Comment by nathandunn** [comment]
This is probably good enough for now.   Minimally, we are now using the root npm structure and build system.    We can make changes to the postinstall script later.

**Comment by enuggetry** [comment]
I can work on it when I'm back from vaca.  I'd like to use it as a package for the JBServer project.  Otherwise seems good to go.

**Pull request merged**
