### PR TITLE
add support for showing a Shine Dalgarno sequence

### PR DESCRIPTION
**Pull request by nathandunn**
Necessary for fix on this PR: https://github.com/GMOD/Apollo/pull/2186 and to fix this issue: https://github.com/GMOD/Apollo/issues/2149 so we don't draw an intron where it should not.

# Submitting a pull request

Please base your pull request based on the "dev" branch of JBrowse

The default branch is "master" but this contains the last stable release, and new pull requests should be based off of "dev"

Then set the base branch to "dev" on GitHub also

### CODE REVIEW

**Comment by cmdcolin** [comment]
Pleast provide sample gff and screenshot of what this looks like. Also this is for a specific track type, NeatHTMLFeatures, and I'm concerned how other track types handle this

**Comment by nathandunn** [comment]
From https://github.com/GMOD/Apollo/issues/2149#issuecomment-504297478

This is what it looks like below.  Its just another biotype in the JBrowse code.  In the Apollo code I have to store it properly to render.   As Apollo renders ONLY in the HTMLFeatures I only fixed it there.   

image

The final GFF3 is:

```
##gff-version 3
##sequence-region NC_001416.1_phage_lambda 1 48502
NC_001416.1_phage_lambda	.	gene	21779	21973	.	+	.	owner=ndunn@me.com;ID=7d4c4954-493d-4d3d-8448-8d666176a2c1;date_last_modified=2019-06-20;Name=CDS.0.1290_0.925232399735;date_creation=2019-06-20
NC_001416.1_phage_lambda	.	mRNA	21779	21973	.	+	.	owner=ndunn@me.com;Parent=7d4c4954-493d-4d3d-8448-8d666176a2c1;ID=c2ec3548-aacf-407b-a44b-a519cba9cb8b;orig_id=CDS.0.1290_0.925232399735;date_last_modified=2019-06-20;Name=CDS.0.1290_0.925232399735-00002;date_creation=2019-06-20
NC_001416.1_phage_lambda	.	CDS	21788	21973	.	+	0	Parent=c2ec3548-aacf-407b-a44b-a519cba9cb8b;ID=1f88fd92-e0cf-4544-9ab7-208d0aff410f;Name=1f88fd92-e0cf-4544-9ab7-208d0aff410f
NC_001416.1_phage_lambda	.	Shine_Dalgarno_sequence	21779	21781	.	+	.	Parent=c2ec3548-aacf-407b-a44b-a519cba9cb8b;ID=1f585c16-1a32-421f-9bb6-f6c04a04fe25;Name=1f585c16-1a32-421f-9bb6-f6c04a04fe25
NC_001416.1_phage_lambda	.	non_canonical_three_prime_splice_site	21788	21788	.	+	.	Parent=c2ec3548-aacf-407b-a44b-a519cba9cb8b;ID=c2ec3548-aacf-407b-a44b-a519cba9cb8b-non_canonical_three_prime_splice_site-21787;Name=c2ec3548-aacf-407b-a44b-a519cba9cb8b-non_canonical_three_prime_splice_site-21787
NC_001416.1_phage_lambda	.	exon	21788	21973	.	+	.	Parent=c2ec3548-aacf-407b-a44b-a519cba9cb8b;ID=9cca3784-fb42-4581-af99-d249e50bbe2d;Name=9cca3784-fb42-4581-af99-d249e50bbe2d
###
```

**Comment by nathandunn** [comment]
The input Shine Dalgarno is here:  https://github.com/GMOD/Apollo/issues/1955#issuecomment-447482035

I was thinking of providing the same fix for Canvas, but I think it renders it properly here:

image

**Comment by cmdcolin** [comment]
I would like a better generic treatment of promoter and gene renderings, but I'll just let this one go if it is very helpful for your purposes.

**Comment by cmdcolin** [comment]
Please use spaces instead of tabs and base PR off of the dev branch in the future

**Comment by nathandunn** [comment]
@cmdcolin  agreed.  This isn't quite a typical promoter, but I'm not thrilled with the final implementation here and there should be a more generic solution.   

Apologies having it go into master.    I have have been looking for `develop` instead and then gave up.

**Pull request merged**
