### PR TITLE
Add ability to set show_tracklabels=0 in config or &tracklabels=0 in url

### PR DESCRIPTION
**Pull request by cmdcolin**
Addresses #868 request, but requires that the hidetracklabels plugin is enabled.

### CODE REVIEW

**Comment by nathandunn** [comment]
thanks . . . let me test it real quick.

**Comment by nathandunn** [comment]
Awesome, thanks.  Works great.

**Comment by bhofmei** [comment]
In case no one noticed, using "&tracklabels=0" in the URL only works when HideTrackLabels plugin is activated. It's not a big deal since it's easy to add the plugin, but this could cause a lot of confusion and it's also a bit annoying when I want to be able to hide track labels but don't want the extra button in the toolbar.

**Comment by cmdcolin** [comment]
true, looks like this user http://gmod.827538.n3.nabble.com/Gmod-ajax-Hide-track-labels-not-working-when-nav-0-td4057922.html noted the same thing

**Comment by cmdcolin** [comment]
oh wait you mention the different issue which is that it only works when plugin loaded which is true ^_^

**Comment by cmdcolin** [comment]
@bhofmei as a stopgap, if you just want the URL parameter to be available and no button e.g. &tracklabels=0 you could replace plugins/HideTrackLabels/js/main.js with this

```
define([
            'dojo/_base/declare',
            'dojo/_base/lang',
            'dojo/query',
            'JBrowse/Plugin'
       ],
       function(
           declare,
           lang,
           query,
           JBrowsePlugin
       ) {
return declare( JBrowsePlugin,
{
    constructor: function( args ) {
        console.log("plugin HideTracksButton constructor");

        var baseUrl = this._defaultConfig().baseUrl;
        var thisB = this;
        var queryParams = dojo.queryToObject( window.location.search.slice(1) );


        if(queryParams.tracklabels == 0 || thisB.browser.config.show_tracklabels == 0) {
            thisB.browser.subscribe('/jbrowse/v1/n/tracks/redraw', function() {
                query('.track-label').style('visibility', 'hidden')
            })
        }
    }

});
});
```

**Comment by bhofmei** [comment]
Thanks for looking into this. I don’t mind having the button. I was just pointing this out for other users. I can imagine someone trying to use &tracklabels=0 in the URL, being confused why it doesn’t work, and having no clue that the HideTrackLabels plugin needs to be activated.

**Pull request merged**
