### PR TITLE
Updated Tabix bed

### PR DESCRIPTION
**Pull request by cmdcolin**
The PR that @zhjilin contributed for #672 was very useful but it was based off of JBrowse 1.11.6

This updates it to fix conflicts and formatting

The code can parse "BED 6", but doesn't require all 6 columns https://genome.ucsc.edu/FAQ/FAQformat.html#format1 (chr start end name score strand)

### CODE REVIEW

**Comment by zhjilin** [comment]
Thanks and nice work @cmdcolin ! I haven't got time to fix my code, been busy to fix something else.

**Comment by cmdcolin** [comment]
No problem. I find the tabix BED to be quite useful in a variety of scenarios, so I've used this branch already for a couple of things. For example, it is great with loading junctions.bed files from tophat or with a large list of variants with scores attached. It actually takes forever for flatfile-to-json.pl to load those files containing potentially millions of lines, but is quite fast to convert to tabix

**Comment by cmdcolin** [comment]
I think this is done if there is interest in reviewing

**Comment by keiranmraine** [comment]
I've had a good play with multiple tracks running BED+tabix.  Should it be possible to use this with the density plot out the box (Track+load from file, select density) or would that be additional config?

**Comment by cmdcolin** [comment]
@keiranmraine it supports the "summary bigwig" when you use the "Track->Open track file or URL" function with the coverage bigwig naming convention (ie. file.bed.gz, file.bed.gz.tbi, file.coverage.bw will become a single track). all the canvasfeatures tracks can use summary bigwigs too via config in trackList.json

**Comment by cmdcolin** [comment]
It might be nice just for completeness sake to allow untabixed BED too. You can already load plain BED with flatfile-to-json.pl but would be good to have the plain JS parser

**Comment by cmdcolin** [comment]
I added a plain BED file parser here :)

I also updated this to not include the "matrix header" parsing code as this seemed non-standard.  As a workaround to enable flexible header parsing, callbacks called commentCallback and featureCallback can be used to preprocess header directives and features

**Comment by cmdcolin** [comment]
There is one other note that I think is important to note about this PR. The files should be named with the particular convention: vcf.gz.tbi or bed.gz.tbi. Having a file like file.bed.gz and file.tbi would be associate the files together

**Comment by cmdcolin** [comment]
I think this is good now, mentioned to @enuggetry about merge! Can go ahead with it?

**Pull request merged**
