### PR TITLE
Accept hyphen for coord ranges.

### PR DESCRIPTION
**Pull request by nathanhaigh**
This PR satisfies #1100 by making the following changes to JBrowse behaviour:

- Accept hyphens (`-`) as the basepair range separator. This is in addition to the currently used `..`
- There is flexibility in the number of hyphens accept in the input, in case of typos.
- ~~Made the hyphen (`-`) the canonical basepair range separator. The legacy `..` is still accepted.~~

### CODE REVIEW

**Comment by nathanhaigh** [comment]
I have some questions about the level of flexibility currently allowed for the coordinate specification - is it needed?

**Comment by nathanhaigh** [comment]
Reverted the last commit which changed the displayed coordinate range separator from `..` to `-`. I'll introduce that proposed change in a new PR.

As this PR stands, it simply introduces `-` as a possible coordinate range separator.

**Comment by cmdcolin** [comment]
This looks good to me, did a pull and it keeps the .. in the location bar but allows - to be used

**Comment by rbuels** [comment]
I feel like the pendulum is swinging toward '-' being canonical, let's see in a day or two.

In the meantime, @nathanhaigh, more locstring parsing tests would be awesome!  Like seq names with colons and seq names with hyphens. :-)

**Comment by nathanhaigh** [comment]
There is still an outstanding issue here. That is JBrowse does not switch to reference sequences with colons when their name is entered into the location search box. I don't think this is to do with the `locstring` parsing since tests show the expected behaviour for strings without basepair coordinates (single point location or a range) return `null`.

Perhaps someone with more familiarity with JBrowse (@cmdcolin @rbuels @keiranmraine ) could take a look? I've added some test data for this (see `tests/data/obscure_contig_names/`).

**Pull request merged**
